apiVersion: v1
kind: Service
metadata:
  namespace: alpha
  name: app
  labels:
    app: app
  #annotations:
    #alb.ingress.kubernetes.io/healthcheck-path: /app/index.html
spec:
  type: NodePort # LoadBalancer
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 80