apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: alpha
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 5
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: rosilva2018/app-alpha:v1
        env:
          - name: AUTHOR
            value: ROSILVA
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: alpha
  name: app
  labels:
    app: app
  #annotations:
    #alb.ingress.kubernetes.io/healthcheck-path: /app/index.html
spec:
  type: NodePort # LoadBalancer
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 80